export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_FRIEND_GROUPS = 'GET_FRIEND_GROUPS' 
export const GET_FRIEND_GROUPS_SUCCESS = 'GET_FRIEND_GROUPS_SUCCESS' 
export const GET_FRIEND_GROUPS_FAILED = 'GET_FRIEND_GROUPS_FAILED' 